### ISSUE TITLE
Please help my open tab addiction

### ISSUE THREAD

**Issue by tomByrer** [surma/ishoudinireadyyet.com#1]
Hi, my name is Tom, & I'm a browser tab addict.
"Hi Tom" 👋 

You can help my tab addiction by not opening new tabs for [every single link](https://github.com/surma/ishoudinireadyyet.com/blob/master/index.hbs#L263-L264) by dropping the `target="_blank"` in the `<a>` elements.  I & many others already have 100+ tabs open in various browsers, no need to open a new tab when the back button works fine ;)
I'm sure browser makers would like us to test how many tabs could be open with out crashing, but perhaps a more automated script would be useful.

**Comment by surma** [comment]
Fair enough ;)
