### ISSUE TITLE
New Edge results

### ISSUE THREAD

**Issue by chicoxyzzy** [surma/ishoudinireadyyet.com#24]
I just found some discussions on [Houdini-related topic](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/aRKT0BkrF-8/Uz06LvMCBgAJ) in Intent to implement group. Chromium-based Edge should be added at some point (after its stable release?). Not sure if old Chakra-based Edge presence in table makes sense though.

**Comment by surma** [comment]
I think I’m going to copy caniuse and just continue to call it Edge, but the version number will be 75+  to make clear that it’s Edgium. And yes, I’ll update this once Edgium goes to stable.
