### ISSUE TITLE
Scrolltimelines aren't implemented in Chrome Canary yet

### ISSUE THREAD

**Issue by blairwilcox** [surma/ishoudinireadyyet.com#5]
We should make note that ScrollTimelines, one of the features mentioned in the Animation Worklet, isn't supported yet in Chrome. Maybe just under **Notes** in the Chrome modal? https://github.com/chromium/chromium/blob/74c0cb98e8b782212794bee0a565e7a4959c2e39/third_party/WebKit/LayoutTests/fast/animation/scroll-animations/animation-created-with-scroll-timeline.html.

**Comment by surma** [comment]
`ScrollTimeline` is support, just not with normal `Animation`, only with `WorkletAnimation`.

I don’t think that’s worth mentioning, would you agree?

**Comment by blairwilcox** [comment]
If it works with `WorkletAnimation`, it's probably not worth mentioning in this context. Thanks for getting back to me so quickly!
