### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by KingOfTac** [surma/ishoudinireadyyet.com#51]
Does the data for the support table come from a specific source, or is it manually updated? It doesn't look like this has been updated in a while. Since this site is one of the top search results for searches on the houdini apis, it would be great if it stayed up to date.

**Comment by surma** [comment]
It is manually updated. It's all in the [data.json](https://github.com/surma/ishoudinireadyyet.com/blob/master/data.json).

It hasn't been updated in a while because I think there's nothing to update. There's hasn't been any significant progress as far as I know.

cc @una

**Comment by KingOfTac** [comment]
Thanks for the update. It's been tough finding up to date information and the current status of everything so it seemed like interest had been lost and this wasn't getting updated anymore. I'll go ahead and close this out.
