### ISSUE TITLE
Custom properties and values API is fully supported in WebKit as of STP 161 and Safari 16.4 beta

### ISSUE THREAD

**Issue by nt1m** [surma/ishoudinireadyyet.com#54]
https://webkit.org/blog/13686/release-notes-for-safari-technology-preview-161/
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

**Comment by chicoxyzzy** [comment]
https://github.com/surma/ishoudinireadyyet.com/pull/55
