### ISSUE TITLE
Add Worklets specification

### ISSUE THREAD

**Issue by SebastianZ** [surma/ishoudinireadyyet.com#9]
The [Worklets Level 1 specification](https://drafts.css-houdini.org/worklets/) is somewhat special, because it is required by the other specifications and doesn't provide a standalone feature for authors.

Nonetheless I think it's worth to list it in the support table to let authors know about it and its implementation status within the browsers.

Sebastian

**Comment by chicoxyzzy** [comment]
+1
Same as [promises](https://jakearchibald.github.io/isserviceworkerready/#promises) on https://jakearchibald.github.io/isserviceworkerready/

**Comment by surma** [comment]
I am going back-and-forth between this as worklets themselves are not a developer-facing API. Additionally, worklets aren’t necessarily implemented as an independent feature. I think, for now, I will opt to not list them.

**Comment by SebastianZ** [comment]
Fair enough. I just thought it would be good to tell people "Hey, the implementers are working on Houdiini and that's the basis for it!", but yeah, Worklets are not really an independent feature.

Sebastian
